### ISSUE TITLE
Lidar Tile Footprint error 

### ISSUE THREAD

**Issue by kataya** [giswqs/WhiteboxTools-ArcGIS#10]
I tested "Lidar Tile Footprint" in WhiteboxTools-ArcGIS(v1.1.0)  using ArcGIS Pro 2.4, but I got an error.
----
Traceback (most recent call last):
  File "<string>", line 21613, in execute
TypeError: lidar_tile_footprint() got multiple values for argument 'output'
----

**Comment by jblindsay** [comment]
@kataya Can you please upload a screenshot? I would need to see the parameters that you ran the tool with to get a better sense of what when wrong. The error message seems to indicated that the tool received multiple values of the `--output` parameter.

**Comment by kataya** [comment]
@jblindsay I uploaded a screenshot.
![LidarTileFootprint_Error_20200217](https://user-images.githubusercontent.com/4308080/74617605-5c4e2180-5171-11ea-9ad6-82bb1c60bddd.png)

From "wb_runner.py", I can execute without error.
![LidarTileFootprint_Runner_20200217](https://user-images.githubusercontent.com/4308080/74617882-c4e9ce00-5172-11ea-8d22-413ed29ef656.png)

**Comment by giswqs** [comment]
@kataya Thanks for reporting! I can confirm that this issue is caused by the ArcGIS front-end only. The WBT backend works fine. I will look into it.

**Comment by giswqs** [comment]
@kataya This issue was caused by the order of the parameters. The WBT Python frontend places the `output` parameter first and the `input` parameter second, whereas the ArcGIS frontend takes the `input` first and the `output` second. I have now forced the ArcGIS frontend to have parameter names explicitly. Therefore, the order of parameters no longer matters. This fix also corrects many other tools with a similar parameter order issue. Thanks again for reporting. 

@jblindsay I noticed there are 13 lidar tools with a default input parameter `i=None`. Normally, the input parameter/file should be required rather than optional. See the screenshot below.

WBT [whitebox_tools.py](https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WBT/whitebox_tools.py#L5985
):
`lidar_tile_footprint(self, output, i=None, hull=False, callback=None)`

Previous ArcGIS frontend
`lidar_tile_footprint(input, output=output, hull=hull)`

Current ArcGIS frontend
`lidar_tile_footprint(i=i, output=output, hull=hull)`

Issue with optional input parameter
![](https://i.imgur.com/C9SYusk.png)

**Comment by jblindsay** [comment]
@giswqs With the LiDAR tools, if the input and output parameters are unspecified, the tool will search for all of the LAS files contained within the working directory and apply the tool to each file. That is the reason why the input and output parameters are optional.

**Comment by giswqs** [comment]
@jblindsay Thanks for the clarification! It makes perfect sense.
