### ISSUE TITLE
Diff. from mean elevation

### ISSUE THREAD

**Issue by xabierr** [giswqs/WhiteboxTools-ArcGIS#22]
I'm running WhiteboxTools-ArcGIS within ArcGIS 10.7 with no issues. However, when trying to run the Diff. from mean elevation using the testdata DEM.tif get the following:  

Traceback (most recent call last):
  File "<string>", line 9663, in execute
TypeError: diff_from_mean_elev() got an unexpected keyword argument 'i'

Failed to execute (DiffFromMeanElev).
Failed at Mon Jul 27 13:39:50 2020 (Elapsed Time: 0.22 seconds

**Comment by giswqs** [comment]
@xabierr Thank you for reporting this bug. It actually affects several tools with dem inputs. In the WBT command line backend program, some tools accept keyword arguments such as `-i`, `--input`, and `--dem`. However, in the Python frontend, most tools with dem inputs only use the `--dem` keyword argument. The only exception is the `Sink` tool, which still uses `-i` argument @jblindsay.  As all tools of the ArcGIS frontend are calling the Python frontend, we need to use `--dem` rather than `-i`. I just committed code to fix this. Please download the latest version and try again. It should be working as expected now.
