### ISSUE TITLE
Many hydrology tools not writing output files in ArcGis Pro

### ISSUE THREAD

**Issue by lukejzw** [giswqs/WhiteboxTools-ArcGIS#23]
Hi, I've been trying to run some of the hydrology tools in ArcGis Pro. While the models appear to be running to completion, they fail to save an output file to the disk which is a bit odd. Any idea why this happening?

**Comment by giswqs** [comment]
What tools are you having issues with?

**Comment by giswqs** [comment]
I just tested some of the tools. It seems the outputs are saved correctly to the hard drive. However, the output are not automatically added to ArcGIS Pro. You can check the output folder and add them manually back to ArcGIS Pro. In ArcMap, outputs are automatically added to the map. Not sure why ArcGIS Pro behaves differently.

**Comment by lukejzw** [comment]
Thanks for having a look. Some of the tools were working for me too but not all. I encountered problems with the Jensen Pour Points and watershed tools. No files were being added to the map or folder when I ran these. Have you tested those particular tools by any chance?

**Comment by giswqs** [comment]
Would you mind sharing a small subset of your files for testing?

**Comment by lukejzw** [comment]
Thanks, here is a link to a folder which contains a flow direction raster and a dams (i.e. pour points) shapefile. Is this useable for you?

https://drive.google.com/file/d/1TtiNpYHoc6lqYo4Y27HPVOqUr3gJ701Y/view?usp=sharing

**Comment by lukejzw** [comment]
Apologies for the slow response, I was busy working on another project. Here is a link with clipped data for the region I am working on. There is a flow direction and stream map raster, as well as a shapefile with dam locations (i.e. pour points to be snapped). Let me know if you can work with this. 

https://drive.google.com/file/d/1uiwwEVVf-20-fxRS6MvDX2OvtAI3Xvw_/view?usp=sharing

**Comment by giswqs** [comment]
The shapefile you shared is complete. Make sure you include shp, shx, dbf, prj, etc.

**Comment by lukejzw** [comment]
Of course, my mistake. Hope it's alright now 
https://drive.google.com/file/d/1blKonPTL0yiqQNMu1s3IURtVJRGpmBj2/view?usp=sharing

**Comment by giswqs** [comment]
I don't think this is an issue of WhiteboxTools. It is probably because you did not do it correctly. The Snap Pour Point needs a D8 Flow Accumulation file, but you sent a D8 flow direction and a stream map. Also, your D8 flow direction seems incorrect. You can also try the [ArcGIS Hydrology Toolset](https://desktop.arcgis.com/en/arcmap/latest/tools/spatial-analyst-toolbox/an-overview-of-the-hydrology-tools.htm). If you can't get your data to work with the ArcGIS Hydrology Toolset, then WhiteboxTools hydrology tools probably won't work for your data either.
