### ISSUE TITLE
Toolbox now only supports ArcGIS Pro.

### ISSUE THREAD

**Issue by M-Bryant** [giswqs/WhiteboxTools-ArcGIS#27]
WhiteboxTools now uses python 3. 
An example of this is the use of Python 3's f-Strings format at line 218 in whitebox_tools.py
Readme.MD should be updated to reflect this toolbox now only supports ArcGIS Pro.

**Comment by jblindsay** [comment]
WhiteboxTools has always used Python 3, since the inception of the project.

**Comment by giswqs** [comment]
@M-Bryant Thank you for pointing this out. It turns out the Line 218 `args.append(f"--license={tool_name}")` caused this issue. Changing it to `args.append("--license={}".format(tool_name))` solves the issue. The toolbox now support both ArcGIS with Python 2.7 and ArcGIS Pro with Python 3.x. 

@jblindsay It seems the f string is only supported by Python 3. Everything else in the whitebox_tools.py is compatible with Python 2.7. The toolbox can be used in ArcMap with Python 2.7 without any problem. 

![image](https://user-images.githubusercontent.com/5016453/126382310-bcb30dfe-3288-4f89-9c44-ebef0fe92866.png)
