### ISSUE TITLE
Tool Openness not recognized

### ISSUE THREAD

**Issue by Geomorph2** [giswqs/WhiteboxTools-ArcGIS#31]
Thank you for all your work on this.  I've been trying to run the openness tool, but I keep running into the same error where it says whitebox_tools.exe doesn't contain a tool called "Openness" (exact message 'Unrecognized tool name Openness.').  Other tools that I've tried do seem to work.

**Comment by giswqs** [comment]
The Openness tool is part of the [WhiteboxTools General Toolset Extension](https://www.whiteboxgeo.com/whitebox-general-toolset/). Running this tool requires a valid license. More info about licensing can be found at https://www.whiteboxgeo.com/services-whitebox-geospatial

**Comment by jblindsay** [comment]
I have just added a list of extension tools to the WBT open-core so that when someone without a license for one of the extension tools tries to run the tool, rather than providing the non-illuminating, 'Unrecognized tool name' error, it should now issue a more informative error: "This tool is part of a Whitebox extension product and there is a missing license. Please contact Whitebox Geospatial Inc. (support@whiteboxgeo.com) to obtaina valid license key."

**Comment by giswqs** [comment]
@jblindsay Sounds good. I will update the Windows binary for the ArcGIS frontend when it is updated. Other frontends should automatically pull the latest binaries from whitebogeo.com during the installation.

**Comment by jblindsay** [comment]
I'm afraid this feature won't be available until the next release of the WBT open-core though and so we will need to wait a bit of time. I don't yet know what the time-frame is for that release.

**Comment by giswqs** [comment]
No worries. Take your time.
